# Generated by Django 5.0.6 on 2024-06-28 05:51

import menu.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to=menu.models.category_preview_directory_path),
        ),
    ]
