# Generated by Django 5.0.6 on 2024-07-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0002_menuitem_available"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menuitem",
            name="available",
        ),
        migrations.RemoveField(
            model_name="menuitem",
            name="image",
        ),
        migrations.AddField(
            model_name="menuitem",
            name="category",
            field=models.CharField(
                choices=[
                    ('Starter', 'Starter'),
                    ('Pasta', 'Pasta'),
                    ('Risotto', 'Risotto'),
                    ('Deep Fried and Burger', 'Deep Fried and Burger'),
                    ('Fish and Seafood', 'Fish and Seafood'),
                    ('Meat', 'Meat'),
                    ('Side Dish', 'Side Dish'),
                    ('Salad', 'Salad'),
                    ('Dessert', 'Dessert'),
                    ('Kid Meal', 'Kid Meal'),
                ],
                default="starter",
                max_length=30,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
