# Generated by Django 5.0.6 on 2024-07-24 09:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0002_menuitem_available"),
        ("menu", "0004_alter_basket_quantity"),
    ]

    operations = []
